# Generated by Django 4.2.5 on 2024-07-27 01:04
import sys
from django.db import migrations


def create_roles(apps, schema_editor):
    if 'test' in sys.argv:
        return
    Role = apps.get_model('authentication', 'Role')
    Role.objects.create(nome='Prestador Serviços', descricao='Descrição para Prestador Serviços')
    Role.objects.create(nome='Cliente', descricao='Descrição para Cliente')
    

class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
