# Generated by Django 4.2.5 on 2024-07-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_auto_20240726_2204"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=6)),
                ("cep", models.CharField(max_length=10)),
                ("estado", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=120)),
                ("foto_perfil", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.perfil",
            ),
        ),
    ]
