# Generated by Django 4.2.5 on 2024-08-02 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('authentication', '0003_perfil_usuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('features', models.ManyToManyField(related_name='users', to='core.feature')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='usuariorole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='usuariorole',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioRole',
        ),
    ]
