# Generated by Django 4.2.5 on 2024-08-03 20:35

import os
from django.db import migrations
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    username = os.getenv('DJANGO_SUPERUSER_USERNAME')
    email = os.getenv('DJANGO_SUPERUSER_EMAIL')
    password = os.getenv('DJANGO_SUPERUSER_PASSWORD')
    
    if not username or not email or not password:
        raise ValueError('DJANGO_SUPERUSER_USERNAME, DJANGO_SUPERUSER_EMAIL and DJANGO_SUPERUSER_PASSWORD must be set')
    superuser = User(
        username=username,
        email=email,
        password=make_password(password),
        is_staff=True,
        is_superuser=True,
    )
    superuser.save()

class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0004_user_remove_usuario_perfil_remove_usuario_roles_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
